react-native/Fable.Helpers.ReactNative.fs
Also added EnableEmptySections on ListView
=> Added ResizeMode type

react-native-barcodescanner/Fable.Helpers.ReactNativeBarcodeScanner.fs, react-native-barcodescanner/Fable.Import.ReactNativeBarcodeScanner.fs, react-native-barcodescanner/README.md, react-native-barcodescanner/package.json
See https://github.com/ideacreation/react-native-barcodescanner
Does it make sense?
=> Initial attempt to map barcode scanner

react-native/Fable.Helpers.ReactNative.fs
Moved ITextStyleAndroid to correct type
Added children to scrollView helper
=> Some small fixes

src/react/Fable.React.Internal.fs
This resolves fable-compiler/fable#651
=> building with latest compiler to fix fable-compiler/fable#651

src/react/Fable.Helpers.React.fs, src/react/Fable.Import.React.fs
=> Adding  and  flexbox css properties

fable-react/Fable.Helpers.React.fs
Related to: https://github.com/fable-elmish/templates/issues/2
=> Add class list helpers

Fable.Helpers.React.fs
Related to #33 
ping @alfonsogarciacaro
=> Add data attribute and borderRadius

Fable.Helpers.React.fs, Fable.Import.React.fs
Added bindings for new Animation and Transition synthetic events.
https://facebook.github.io/react/docs/events.html#animation-events
=> Add Animation and Transition events

README.md
=> Adding to README.md clarification for #40

src/Fable.React/Fable.Helpers.React.fs, src/Fable.React/Fable.Import.React.fs
=> Add helpers for stateful components

README.md, Samples/SSRSample/build.fsx, Samples/SSRSample/src/Client/View.fs, docs/server-side-rendering.md, src/Fable.React/Fable.Helpers.Isomorphic.fs, src/Fable.React/Fable.Helpers.React.fs, src/Fable.React/Fable.Helpers.ReactServer.fs
Sorry that I forgot to handle null elements in the last PR, 😅 this PR will fix it.
Also, I wrote a simple tutorial about server-side rendering, not sure it's clear enough.
=> Add a simple tutorial about server-side rendering

README.md, Samples/SSRSample/src/Client/Bench.fs, Samples/SSRSample/src/Client/View.fs, Samples/SSRSample/src/Client/index.css, Samples/SSRSample/src/Client/index.html, Samples/SSRSample/src/Client/jsComp.js, Samples/SSRSample/src/Server/Server.fs, docs/server-side-rendering.md
Add more some introduction and guidance about SSR in tutorial for https://github.com/fable-compiler/fable-react/pull/65#issuecomment-369936742
Add some css for SSR Sample App for https://github.com/fable-compiler/fable-react/pull/69#issuecomment-369938567
=> Update SSR tutorial and Sample

docs/server-side-rendering.md
=> Fix SSR docs format

Samples/SSRSample/benchmark/dotnet.fs, Samples/SSRSample/benchmark/node.js, Samples/SSRSample/build.fsx, docs/server-side-rendering.md, src/Fable.React/Fable.Helpers.ReactServer.fs
* Uses HashSet instead of Set
* Uses a single StringBuilder for rendering
=> Speed-up Server-Side rendering

src/Fable.ReactGoogleMaps/README.md
=> Correct create LatLngLiteral in readme.

src/Fable.ReactGoogleMaps/README.md
=> Corrected last createLatLng example

src/Fable.React/Fable.Helpers.ReactServer.fs
=> Added #if !FABLE_COMPILER

src/Fable.React/Fable.React.Props.fs, src/Fable.React/Fable.ReactServer.fs
See :
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role
=> Add aria-controls and aria-pressed HtmlAttributes

src/Fable.React.Helpers.fs
* Change `equalsButFunctions` to stop early when a difference is found instead of continuing to compare the rest of the properties
* Provide another variant `memoEqualsButFunctions` using reference equality instead of F# one. There result is that it should do the same thing as the the default memo equality except that it ignore functions
=> Faster equality

src/Fable.React.Helpers.fs
I find these descriptions a bit more clear. But please check for errors; I may have misunderstood some details.
By the way, how do both of these functions work with tuples? Perhaps that should be mentioned, too?
=> Clarify function docs

src/Fable.React.fs
It would be useful to be able to forwardRef when creating Functional Components.
=> Add forwardRef ?

package-lock.json, src/Fable.React.Hooks.fs
Adding `use-reducer` in the style of `use-state`.
https://reactjs.org/docs/hooks-reference.html#usereducer
Related to #140
=> Use reducer

src/Fable.React.Props.fs
Source: w3 doc in https://www.w3.org/TR/wai-aria/#aria-atomic
=> Add aria-XXX attributes

src/Fable.React.FunctionComponent.fs
Sorry @MangelMaxime! At the end I managed to reproduce the issue, I had to modify a piece of code outside the Inbox.EmailMeta component. I got it fixed by applying your trick in `HMR.equalsButFunctions` :+1:
=> FunctionComponent: Suspend memoize during HMR

src/Fable.ReactServer.fs
fixes issue https://github.com/fable-compiler/fable-react/issues/215
=> Optimize cssPropsCache https://github.com/fable-compiler/fable-react/issues/215

src/Fable.React.Hooks.fs
Ass discussed in https://github.com/fable-compiler/Fable/issues/2826
=> Add useLayoutEffect

src/Fable.React.Types/Fable.ReactDom.fs
https://reactjs.org/docs/react-dom.html#flushsync
=> Add flushSync

src/Fable.React/Fable.React.Props.fs, src/Fable.React/Fable.React.fsproj, src/Fable.React/RELEASE_NOTES.md
Fix #237.
Used order from: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/220087807a5746367416c2a3ef87c17d7344f22f/types/react/index.d.ts#L1533
=> Added Pointer Events
