fable-compiler/fable-react

react-toolbox/Fable.Helpers.ReactToolbox.fs, react-toolbox/README.md, react-toolbox/package.json
Adding bindings for react-toolbox as per [fable-react-toolbox](https://github.com/2sComplement/fable-react-toolbox). Most components are working but further modifications to props are likely.
=> Adding react-toolbox bindings

react-native/Fable.Helpers.ReactNative.fs
The picker helpers used the import types as its parameters instead of the keyvaluelist DUs defined in the helpers file
=> Fixed picker helpers use wrong type

react-native/Fable.Helpers.ReactNative.fs, react-native/Fable.Import.ReactNative.fs
Moved Animated module on top - used by navigation experimental.
Fixed a few nested type refs.
Removed NavigationAnimatedView, as it was already deprecated.
Converted a few required properties into constructor args.
Added a bunch of missing types to Import by hand, looking at JS sources.
=> fixing nested types, adding experimental navigation types and constructors

react-native/Fable.Helpers.ReactNative.fs, react-native/Fable.Import.ReactNative.fs
Inferring from JS sources the properties for cardStack, header and utils.
Breaking: all "touchable" constructors now take children.
Also, addressing some missed opportunities for covariance of props.
=> experimental navigation refinements

src/react-native/Fable.Helpers.ReactNative.fs
TextInput cannot have child elements and the text should set in the props rather than in the children. According to a user on gitter:
> When I try to make use of TextInput, passing it an arbitrary string, I get "Raw text cannot be used outside of a <Text> tag. Not rendering string: "foo""
He confirmed that using this alternative works:
```fsharp
let textInput (props: ITextInputProperties list) : React.ReactElement  =
R.from (RN.TextInput) (unbox props) []
```
Which is the same as 
```fsharp
let textInput (props: ITextInputProperties list) : React.ReactElement  =
createElement(RN.TextInput, props, [])
```
=> Remove (text: string) arg from TextInput

Fable.Helpers.React.fs, Fable.Import.React.fs
Also related to #33 
@MangelMaxime please review, I've renamed Width in HTML and SVG props to avoid conflicts, but maybe this is more confusion for users, what do you think?
To my surprise, the problem with mixed properties in SVG elements has been fixed just by removing the `#` in `svgEl` signature. You shouldn't have to cast to `IProp` anymore :)
The last fix we could do is just replace all the `U2<float, string>` with just `obj`. We'll lose a bit of type safety but we don't need to use the `!^` operator constantly (which @forki and I guess others don't like that much :wink:) and ints would also be accepted.
=> Some API improvements

src/Fable.React/Fable.Helpers.React.fs
Unless I'm missing something, it's hard to make an SVG rectangle without a Height tag.  There is a matching Width attribute.  Also useful for specifying the SVG element's size as well.  Apologies if I'm missing something deeper.
=> SVGAttr attribute Height added to match Width

src/Fable.React/Fable.Import.React.fs
Add abstract lifecycle methods for Component class, then we can override lifecycle methods with intellisense and type check.
=> Make Component's lifecycle methods under type-check

src/Fable.React/Fable.Helpers.React.fs, src/Fable.React/Fable.Import.React.fs
At the beginning I wrote the helper names to be as short as possible (`com` to instantiate a component from a type, `fn` from a function, `str` from string, etc). But I think this is confusing for new users and React allows more types to be accepted as elements or as the return value of `render()` (numbers, arrays...).
We're going to introduce some breaking changes in 1.3 (now you'll have to use `override` for the `render()` method) so maybe it's good time to try to uniform the helpers API. I was thinking to use more meaningful names prefixed by `of`. The old names would still be valid but they would be marked as obsolete so users can update them. What do you think? @forki @MangelMaxime @et1975 @zaaack 
```
ofType
ofFunction
ofImported
ofString
ofOption
ofInt
ofArray
...
```
=> New uniform names for helpers

src/Fable.React/Fable.Helpers.React.fs
When I tried to write inline style for box-shadow css property, I found out that it is missing in CSSProp discriminated union. So here is a fix.
=> Add BoxShadow CSSProp

src/Fable.React/Fable.Helpers.React.fs, src/Fable.React/Fable.Import.React.fs
* Add PureComponent doing shallow state & props comparison to avoid `render()` being called.
* Also add a PureStatelessComponent alias to PureComponent taking no state type parameter. Such components are mapping perfectly to an elm-like architecture with immutable props and no mutable state.
* Add `Fragment` (class) and `fragment` helper function to easily return lists from `render()`
=> Add React PureComponent and Fragment

src/Fable.React/Fable.Helpers.React.fs, src/Fable.React/Fable.Import.React.fs
(Not sure if you'll want this per issues described below, but submitting at least for consideration/discussion.)
I noticed some fairly typical CSS properties like background-position/background-size weren't represented. Rather than spot-add them, I went ahead and scraped https://developer.mozilla.org/en-US/docs/Web/CSS/Reference and https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute for a more complete list.
Many are experimental/draft settings, but the original list already had some of those so I just left everything in. I'm not sure if the library wants to be in the business of judging what to include/exclude, or leave it to the user.
Note, I didn't test everything added, just a few I was interested in. I converted all hyphen separators to camelCase/PascalCase assuming that …
=> Added many CSS props sourced from MDN. Changed all CSS types to obj.

src/Fable.React/Fable.Helpers.React.fs
Removed ICSSProp as it was only implemented by CSSProp and therefore only added extra casting for no gain. Style helper now takes CSSProp directly. Any users that were explicitly referencing ICSSProp type will need to change. Fixes #56.
=> Removed ICSSProp to reduce casting (fix #56)

Samples/SSRSample/benchmark/dotnet.fs, Samples/SSRSample/benchmark/dotnet.fsproj, Samples/SSRSample/benchmark/node.js, Samples/SSRSample/benchmark/paket.references, Samples/SSRSample/build.fsx, Samples/SSRSample/src/Client/Client.fs, Samples/SSRSample/src/Client/Client.fsproj, Samples/SSRSample/src/Server/Server.fs, docs/server-side-rendering.md
As @forki said on Twitter: https://twitter.com/sforkmann/status/969912930501300224 
I added a multi-thread version benchmark in SSRSample, this time I tested in a more clean environment, with all applications that might increase system's load like Chrome, VSCode closed (which I really should do at the first benchmark 😅 ). 
The good news is that fable-react on dotnet core is still faster then `ReactDOMServer` on nodejs, and even faster. In my macbook (2.7 GHz Intel Core i5, 4 processors), it's about ~4x faster in a single thread, and still about ~3x faster in 4 threads/workers!
=> Add multi-thread benchmark for SSR

src/Fable.React/Fable.Helpers.React.fs, src/Fable.React/Fable.Helpers.ReactServer.fs, src/Fable.React/Fable.React.fsproj
Fix https://github.com/fable-compiler/fable-react/issues/82 via adding some compiler directives, it's strange that the ionide can also emit diagnosticses after I run `dotnet build` in Fable.React...
@alfonsogarciacaro @MangelMaxime Plz review, thx~
=> Fix netstandard1.6 & style mismatch with client (fix 82)

README.md, docs/using-third-party-react-components.md
This is a first stab at documenting how to use a third party react component. Please let me know what you think!
=> Document use of third party react components (#84)

docs/using-third-party-react-components.md
I was really confused for an embarrassingly long time ;D
=> Fix namespace Fable.React => Fable.Helpers.React

docs/using-third-party-react-components.md
I was really frustrated why I just imported ``undefined`` until I compared the generated Javascript against the example and noticed the extra ``{`` ``}``.
=> Put more emphasis on there being multiple exports/imports, add example for default import

src/Fable.React/Fable.Helpers.React.fs
There is a discriminated union for HTMLAttr which has an #if !FABLE_COMPILER at the end and the type has the interface IHTMLProp.
```fsharp
type HTMLAttr =
| DefaultChecked of bool
| DefaultValue of string
...
#if !FABLE_COMPILER
| Style of CSSProp list
| Data of string * obj
#endif
interface IHTMLProp
```
Then, later in the same module, there is an inline function called "Data" inside of an #if FABLE_COMPILER.
```fsharp
#if FABLE_COMPILER
let inline Style (css: CSSProp seq): HTMLAttr =
!!("style", keyValueList CaseRules.LowerFirst css)
let inline Data (key: string, value: obj): IHTMLProp =
!!("data-" + key, value)
#endif
```
Fulma uses the Data function in the Divider module. When building the Fulma docs, the compiler emits a warning. 
WARNING in ../src/Fulma.Extensions/Divider.fs …
=> Inconsistent types across a compiler directive cause build warnings when using Fable.React.Helpers

src/Fable.React/Fable.Import.React.fs
as per https://github.com/fable-compiler/fable-react/issues/104, with message to use setState(updater: 'S->'P->'S) instead.
=> Marked setState(s: 'S) as Obsolete

src/Fable.React/Fable.Helpers.ReactServer.fs
Raw.writeTo accepts a HTMLNode while constructed model outputs a ReactElement.
The code already provides a private castHTMLNode function for conversion.
This PR make it public to be used from the outside.
The implementation has also been changed to make it safer. Any non matching input now returns a HTMLNode.Empty instead of throwing an exception.
=> Make castHTMLNode public for use with Raw.WriteTo

src/Fable.React/Fable.Helpers.React.fs
It also add to the helper types the concept of a `ReactComponentType` (Something that can be passed to createElement). Some of the types exists in the typescript-imported part of the library but they aren't really adapted and try to handle lot of things that are now obsolete.
They will also be necessary to import `React.lazy`
I didn't add any higher level helpers but one I find useful is the capability to create a named memo without passing the comparer :
```fsharp
let namedMemo<'props> (name: string) (f: 'props -> ReactElement): ReactComponentType<'props> =
f?displayName <- name
memo(f, None)
// Usage
type HelloProps = { Name: string }
let helloWorldComponent = namedMemo "HelloWorld" (fun props ->
span [] [str "Hello "; str props.Name]
)
let helloWorld name = ofElementType …
```
=> Add React.memo

src/Fable.React/Fable.Helpers.React.fs
React use `null` to signal that nothing should be rendered, it could be done before with `ofOption None` but this add clearer alternative to generate this.
```fsharp
let render props =
let details =
match props.Details with
| Some d -> strong [] [str (sprintf " (%s)")] d
| None -> nothing
span [] [ str props.Name; details ]
```
=> Add nothing to react helpers

src/Fable.React/Fable.Helpers.React.fs
This is a breaking change to memo and memoWith !
They become builder functions, producing functions that can be directly used in a render method and don't support children.
The high-level version are still available in the ReactElementType module for anyone wanting the more complete experience (Like children support, or later returning component types themselves to use in `lazy`).
Sample usage :
```fsharp
type HelloProps = { Name: string }
let hello = memo "Hello" <| fun { Name = name } ->
span [str "Hello "; str name]
let view model =
hello { Name = model.Name }
```
=> Simplify memo usage by default

src/Fable.React.Props.fs
This PR adds a couple of type definitions to make usage of CSS properties type-safe. It is not much but it only covers a couple of commonly used inline styles:
This is of course a *breaking* change because the properties such as `Display` were taking `obj` as input where the user supplies a string a everything works out (hopefully) but now the types are restricted to the defined DU's
This PR doesn't affect bundle sizes. All DU's are simple `StringEnum`s. 
I thought it would be a good time to work on these breaking changes since we are already updating to a major version.
=> Add type-safe css properties

src/Fable.React.FunctionComponent.fs
Memo when used with a comparison function create a named node
in the React debugger.
The node is named 'Memo' by default and we change it to
'Memo(displayName)' if a displayName is passed to FunctionComponent.Of
=> Name memo elements

src/Fable.React.FunctionComponent.fs
Reading through the [Fable.React 5 blog post](https://fable.io/blog/Announcing-Fable-React-5.html), I was confused by the fact that `React.memo` wasn't mentioned anywhere. Digging into the code, it seems to me that the new `FunctionComponent.Of` uses `React.memo` when `memoizeWith` is specified. I think it would be best to mention this is the function's documentation.
=> Clarify what FunctionComponent.Of does

src/Fable.React.Props.fs, src/Fable.ReactServer.fs
To get my feet wet regarding the strengthening of the[ type-safety of the CSS dsl](https://github.com/fable-compiler/fable-react/issues/150#issuecomment-524199843).
I've added options for overflow and its cousins overflow-x and overflow-y, accoding to the [spec](https://drafts.csswg.org/css-overflow-3/#propdef-overflow). All comments on the options are directly copied from their description in the spec.
=> Add type bindings for overflow, overflow-x and overflow-y options

src/Fable.React.Props.fs
I noticed that `WhiteSpace WhiteSpaceOptions.PreLine` was not working. 
If there is not an option missing, Compiled Name has to be set for a lot of props.
=> WIP: Missing hyphens for typed css props

src/Fable.React.Props.fs
CssProps are, unlike their options, no string enums. They MUST not have any hyphen.
fixes #182
=> Removed Hyphen from CssProp

src/Fable.React.Props.fs
Support for CSS JustifySelf  (https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self)
It's still working draft, but we have JustifyContent anyway.
They'll probably move the grid spec to recommendation soon.
=> Added JustifySelf used in Grid containers

Samples/SSRSample/webpack.config.js
Attempting to launch the SSRSample gives `ReferenceError: webpack is not defined`.
=> Fixes webpack ReferenceError for SSRSample

Samples/TodoMVC/src/TodoMVC.fs, Samples/TodoMVC/src/TodoMVC.fsproj, Samples/TodoMVC/webpack.config.js, src/Fable.React.FunctionComponent.fs, src/Fable.React.Helpers.fs, src/Fable.React.fsproj
**TL;DR** To use the new API, change the code as follows:
```fsharp
// Declaring site. Before:
let MyComponent = FunctionComponent.Of(fun (props: {| value: string |} -> (* view code *))
// Now (note `displayName` argument is not needed any more):
type MyComponent() =
inherit FunctionComponent<{| value: string |}>(fun props -> (* view code *))
// Call site. Before:
MyComponent {| value = foo |}
// Now (use type alias if you find it too verbose: `type C = FunctionComponent`)
FunctionComponent.Render<MyComponent,_> {| value = foo |}
```
--------------------
When React hooks were out and functions became the preferred way to define React components, we tried to use the opportunity to move away from the class components as the syntax was a bit messy and promote the use of React components, so …
=> New API for FunctionComponent

src/Fable.ReactServer.fs
This PR fixes notation in SSR for some of the predefined SVG attributes. The changes are made according to this reference: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute
=> Fix notation for SVG attributes SSR

src/Fable.React.Helpers.fs
A simple shorthand to get rid of an annoying pipe when rendering a formatted string:
`div [] [ sprintf "Hello, %s. It is %A" user DateTime.Now |> str ]`
=>
`div [] [ strf "Hello, %s. It is %A" user DateTime.Now ]`
=> Introduce strf

src/Fable.React.FunctionComponent.fs
In `FunctionComponet.Lazy` we should not return an empty `div` for SSR. Instead we should return the original component.
Original issue #222
=> Fallback to original component in FunctionComponent.Lazy for SSR

src/Fable.React/Fable.React.FunctionComponent.fs, src/Fable.React/Fable.React.fsproj, src/Fable.React/RELEASE_NOTES.md
User code that invokes `FunctionComponent.Of` can also be in generic context which makes caching by source FileName+LineNumber unsuitable:  one function gets cached and resolved at runtime for different runtime types which results in runtime exceptions.
I propose to add `'Props` type name to the cache key to fix that.
You still can write code were wrong function will be picked up at runtime for the same 'Props argument type (e.g. if different `render` func values are passed from the outside), but it's less likely to happen. 
Ultimate solution would be to expose the fact that function is prepared and cached to the users and let them to specify their own unique cache key - or piggyback on existing `displayName`, which is also not ideal.
=> FunctionComponent.Of extend func cache key with 'Props type name
